codebase_path: "."
output_docs_folder_name: "docs"
ignore_folders:
  - "venv"
file_types:
  - ".py"
single_file: False
override_ai_prompt:
  - "You are a highly skilled software engineer and software architect"
  - "You are analysing another persons code and writing a report on each file in a codebase"
  - "You will provide feedback for each file and suggest improvements where necessary"
  - "The code is centred around NVIDIA DeepStream integration and the processing of multiple AI models"
  - "The inferencing for some of those models will be sent to NVIDIA Triton Inference server for better performance"
  - "Please give a detailed account of how every Class, method, decorator, and important variable works in the code and its intention"
  - "Lay everything out so a new developer can really understand what the code is supposed to do"
  - >
    Use properly formatted Markdown,  assume the file already has a Markdown title and follow the format:

    ## Purpose of file

    Loads the application configuration etc...

    ## Feedback

    Feedback about what could be improved and changed goes here...

    ## Things to refactor

    Mention any unused import, variables, methods, etc., that should be removed. Hightlight possible improvements here in the code, such as optmisations.

    ## Components of the file

    ### Class: frameObj
    Purpose: Some description here...
    Methods: 
        1. __init__ (list vars here...)
          Initialises the class and etc...
        2. addObject (list vars here...)
          Something here...
          
    ### Method: do_something (list vars here...)
    Purpose: Some description

    ### Variable: HELLO_WOLRD
    Purpose: Stores some value for etc...
