version: "3"
services:
  app:
    container_name: auto-codebase-documenter
    build: .
    command: python ./documenter.py
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
