codebase_path: "."
output_docs_folder_name: "docs"
ignore_folders:
  - "venv"
  - "temp"
  - ".git"
  - "tests"
is_ignore_gitignore: True
file_types:
  - ".py"
unwanted_files: None
skip_existing: False
gpt_model: "gpt-3.5-turbo"
language: "en"
    